### ISSUE TITLE
I am getting some undefined errors.

### ISSUE THREAD

**Issue by guptara** [sahmad98/Distance_measurement_using_single_camera#2]
![distance measurement errors](https://user-images.githubusercontent.com/34390566/33924464-32c2ebc2-dffc-11e7-81ea-65c9f32e2c24.png)

![untitled](https://user-images.githubusercontent.com/34390566/33924537-7b4a0222-dffc-11e7-963a-09d65dfb8cb3.png)

**Comment by sahmad98** [comment]
Have you included the OpenCV headers?

Also add the library to the link path.

**Comment by guptara** [comment]
yes i have included headers like stdafx.h tchar.h and other where already
included in source code. Now what should i do?

I am getting identifer undefined error like for VideoCapture cam(1) -
"identifer VideoCapture" undefined.

And for others too i am getting same error.

please help me to solve this.....

**Comment by sahmad98** [comment]
The case could be either you are not adding the include files properly or the version of openCV you are currently using doesn't have VideoCapture class. I guess i had used OpenCV 2.3. See for VideoCapture class in headers.

**Comment by guptara** [comment]
I am using *OPENCV 3.1.0* with *Visual studio 2015*. is it ok?
&
Can you tell me which *include files *should i use ?

On Dec 16, 2017 9:05 PM, "Saleem Ahmad" <notifications@github.com> wrote:

The case could be either you are not adding the include files properly or
the version of openCV you are currently using doesn't have VideoCapture
class. I guess i had used OpenCV 2.3.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/sahmad98/Distance_measurement_using_single_camera/issues/2#issuecomment-352190659>,
or mute the thread

**Comment by sahmad98** [comment]
https://docs.opencv.org/3.1.0/d8/dfe/classcv_1_1VideoCapture.html#details

Take this as a reference. You might need to do a little bit research and modify the code accordingly.

**Comment by guptara** [comment]
Thank you sir. All my errors have been solved now just because of your help
and guidance.
but sir at the time of debugging, output windows appears and get closed
suddenly and prompt me with this

*Unhandled exception at 0x00007FF9ED341F28 in Distance Measurement.exe:
Microsoft C++ exception: cv::Exception at memory location
0x000000CD771DAFB0.*

can you help me with this please.

**Comment by sahmad98** [comment]
You need to debug the program and watch the variables for any null pointer.

**Comment by guptara** [comment]
sir i debugged the program but i am getting *unhandled exemption* again and
agian.
i searched this in google but i am not getting significant answer to solve
this problem.
i don't understand the problem for this error and how to solve this.
